### ISSUE TITLE
Can this be used in production?

### ISSUE THREAD

**Issue by xwiz** [charlesinto/monnify-reactnative-sdk-v2#1]
Noticed this is not on NPM yet, is it safe to use in production? Any gotchas?

**Comment by charlesinto** [comment]
Yes, it can be used on production, however, an update is been made on iOS and it is on npm. The link can be found below.

`https://www.npmjs.com/package/monnify-react-native-v2`

**Comment by xwiz** [comment]
OK great work. Would be great to also have a webview version which can be compatible with expo

**Comment by charlesinto** [comment]
Thanks, @xwiz. we will consider it
